---
- hosts: all
  connection: local

  vars_files:
    - config.yml

  roles:
    - role: geerlingguy.homebrew
      tags: ['homebrew']

    - role: pip
      tags: ['pip']

    - role: dotfiles
      tags: ['dotfiles']
