" Use Vim settings, rather then Vi settings. This setting must be as early as
" possible, as it has side effects.
set nocompatible

" load Vundle & plugins
if filereadable(expand("~/.vimrc.bundles"))
  source ~/.vimrc.bundles
endif

filetype plugin indent on

" Leader
let mapleader = " "
" swap : and ;
nnoremap ; :

let &t_Co=256

set background=dark
colorscheme base16-default

set hidden
set backspace=2   " Backspace deletes like most programs in insert mode
set nobackup
set nowritebackup
set noswapfile    " http://robots.thoughtbot.com/post/18739402579/global-gitignore#comment-458413287
set history=50
set showcmd       " display incomplete commands
set incsearch     " do incremental searching
set laststatus=2  " Always display the status line
set autowrite     " Automatically :write before running commands
set autoread
set nowrap        " dont wrap words
set scrolloff=10
set mouse=c       " turn off mouse
set hlsearch      " highlight search results
set textwidth=0
set colorcolumn=0
set smartindent
set ignorecase
set smartcase

" wildmenu
set wildmenu
set wildmode=full:longest,full

" Whitespace
set list
set listchars=tab:>.,trail:.,extends:\#,nbsp:.

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
if (&t_Co > 2 || has("gui_running")) && !exists("syntax_on")
  syntax on
endif


augroup vimrcEx
  autocmd!

  " When editing a file, always jump to the last known cursor position.
  " Don't do it for commit messages, when the position is invalid, or when
  " inside an event handler (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif

  " Set syntax highlighting for specific file types
  autocmd BufRead,BufNewFile Appraisals set filetype=ruby
  autocmd BufRead,BufNewFile *.md set filetype=markdown

  " Enable spellchecking for Markdown
  autocmd FileType markdown setlocal spell

  " Automatically wrap at 80 characters for Markdown
  autocmd BufRead,BufNewFile *.md setlocal textwidth=80

  " Allow stylesheets to autocomplete hyphenated words
  autocmd FileType css,scss,sass,html,haml setlocal iskeyword+=-

  " set tab width for Go Lang
  autocmd FileType go setlocal shiftwidth=8 tabstop=8


augroup END


" Softtabs, 2 spaces
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

" ; ,
nnoremap 8 ,
nnoremap 9 ;

" CTRL P
let g:ctrlp_user_command = 'ag %s -l --nocolor -g ""'
let g:ctrlp_use_caching = 0
let g:ctrlp_custom_ignore = {
  \ 'dir':  '\.git$|\.yardoc\|vendor/bundle|public$|log\|tmp$',
  \ 'file': '\.so$\|\.dat$|\.DS_Store$|\.jpg$',
  \ }


" get rid of last search highlight
nnoremap <CR> :noh<CR>

" Line numbers
set number
set numberwidth=5

" Tab completion
" will insert tab at beginning of line,
" will use completion if not at beginning
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<tab>"
    else
        return "\<c-p>"
    endif
endfunction
inoremap <Tab> <c-r>=InsertTabWrapper()<cr>
inoremap <S-Tab> <c-n>

" Switch between the last two files
nnoremap <leader><leader> <c-^>

" Get off my lawn
" nnoremap <Left> :echoe "Use h"<CR>
" nnoremap <Right> :echoe "Use l"<CR>
" nnoremap <Up> :echoe "Use k"<CR>
" nnoremap <Down> :echoe "Use j"<CR>

" Treat <li> and <p> tags like the block tags they are
let g:html_indent_tags = 'li\|p'

" Open new split panes to right and bottom, which feels more natural
set splitbelow
set splitright

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Always use vertical diffs
set diffopt+=vertical

" insert binding.pry easily
nnoremap <c-a> orequire 'pry'; binding.pry<Esc>
inoremap <c-a> require 'pry'; binding.pry<space>


" line/column highlighting
function! LinePing()
  set cursorline
  redraw
  sleep 50m
  set nocursorline
endfunction

nmap <leader>L :call LinePing()<CR>

let g:airline_powerline_fonts = 1

" easily copy/paste with system clipboard
vnoremap <leader>c "*y
noremap <leader>v "*p

" easier movement around tabs
nnoremap <leader>] gt
nnoremap <leader>[ gT

" splits resize
nnoremap <leader>. 20<C-w>>
nnoremap <leader>, 20<C-w><
nnoremap <leader>= <C-w>=

" Spin calling copied from
" https://github.com/jareks/dotfiles/blob/master/vim/.vimrc
map <leader>s <ESC>:call CallSpin()<CR>
map <leader>f <ESC>:call SetSpinCall(expand("%"), 0)<CR>:call CallSpin()<CR>
map <leader>l <ESC>:call SetSpinCall(expand("%"), line("."))<CR>:call CallSpin()<CR>

function! SetSpinCall(filename, linenum)
  let g:spin_test_file = a:filename
  let g:spin_test_line = a:linenum
endfunction

function! CallSpin()
  if g:spin_test_line
    execute "Dispatch! spin push " . g:spin_test_file . ":" . g:spin_test_line
  else
    execute "Dispatch! spin push " . g:spin_test_file
  endif
endfunction

" Rename current file
function! RenameFile()
  let old_name = expand('%')
  let new_name = input('New file name: ', expand('%'), 'file')
  if new_name != '' && new_name != old_name
    exec ':saveas ' . new_name
    exec ':silent !rm ' . old_name
    redraw!
  endif
endfunction

map <leader>R :call RenameFile()<CR>

" Ag shortcuts - open Ag in new tab
function! SearchInNewTab()
  let g:word_to_search = expand("<cword>")
  tabe
  execute "Ag " g:word_to_search
endfunction

map <leader>G :call SearchInNewTab()<CR>
map <leader>g :Ag<space><C-r><C-w><CR>
map <leader>a :Ag<space>

" Disable ex mode
map Q <Nop>

map <leader>o ;Dispatch! chrome-cli open http://<space>

" Quick mappings for <leader>t
"
" Map <leader>t to activate and reload chrome tab
function! MapForChromeReload(tab_id)
  execute "map <leader>t :Dispatch! chrome-cli activate -t " a:tab_id " && chrome-cli reload<CR>"
endfunction
command! -nargs=1 MapForChromeReload call MapForChromeReload(<f-args>)


" Rails edit shortcuts
map <leader>rc :Econtroller<space>
map <leader>rv :Eview<space>
map <leader>rm :Emodel<space>
map <leader>rh :Ehelper<space>
map <leader>re :Eenvironment<space>
map <leader>ri :Einitializer<space>
map <leader>rx :Rextract<space>


" Reload currently open windows
function! ReloadOpenWindows()
  set noconfirm
  windo e!
  set confirm
endfunction

map <leader>1 :call ReloadOpenWindows()<CR>

" Move line up/down
nnoremap U ddkP
nnoremap Y ddp

