# Base16 Shell
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

export PATH=/usr/local/bin:$PATH

export LC_ALL=pl_PL.UTF-8
export LANG=pl_PL.UTF-8

# GoLang workspace
export GOPATH=$HOME/Projects/Go
export PATH=$PATH:$GOPATH/bin

export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/jploskonka/Desktop/google-cloud-sdk/path.zsh.inc' ]; then source '/Users/jploskonka/Desktop/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/jploskonka/Desktop/google-cloud-sdk/completion.zsh.inc' ]; then source '/Users/jploskonka/Desktop/google-cloud-sdk/completion.zsh.inc'; fi

export EDITOR=vim

# Plugins
# use Antigen for plugins management
source $(brew --prefix)/share/antigen/antigen.zsh

# Load oh-my-zsh library
antigen use oh-my-zsh

# git
antigen bundle git
# syntax highlighting
antigen bundle zsh-users/zsh-syntax-highlighting

antigen apply

# Remove git dirty indicator from git_prompt_info
function git_prompt_info() {
  if [[ "$(command git config --get oh-my-zsh.hide-status 2>/dev/null)" != "1" ]]; then
    ref=$(command git symbolic-ref HEAD 2> /dev/null) || \
    ref=$(command git rev-parse --short HEAD 2> /dev/null) || return 0
    echo "%{$fg[blue]%}${ref#refs/heads/}%{$reset_color%}"
  fi
}

# Change git_prompt_info format
ZSH_THEME_GIT_PROMPT_DIRTY="%{$fg[red]%} ✗ %{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN=" "

# Vim mode + some useful shortcuts
bindkey -v
bindkey '^r' history-incremental-search-backward
bindkey '^?' backward-delete-char # backspace working after return from command mode
# Use vim cli mode
bindkey '^P' up-history
bindkey '^N' down-history

# go to beginning and end of line with Emacs shortcuts
bindkey '^A' beginning-of-line
bindkey '^E' end-of-line

# Set left and right prompts
function zle-line-init zle-keymap-select {
    VIM_NORMAL="%{$fg[blue]%} [% CMD]% %{$reset_color%}"
    VIM_INSERT="%{$fg[red]%} [% INS]% %{$reset_color%}"


    # Set left and right prompt
    PROMPT="%{$fg[green]%}%~%{$reset_color%}${${KEYMAP/vicmd/$VIM_NORMAL}/(main|viins)/$VIM_INSERT}$(parse_git_dirty)"
    RPROMPT="$(git_prompt_info)%{$reset_color%}"
    zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select
export KEYTIMEOUT=1

# Default left prompt
export PROMPT="%{$fg[green]%}%~%{$reset_color%}$VIM_INSERT "

# Init rbenv
eval "$(rbenv init - zsh)"


# https://github.com/nvbn/thefuck
alias fuck='$(thefuck $(fc -ln -1))'
alias FUCK='fuck'

ulimit -n 10240

# Shell aliases
source ~/.aliases

